//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirdTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MAIN_WINDOW_TOP {
            get {
                return ((double)(this["MAIN_WINDOW_TOP"]));
            }
            set {
                this["MAIN_WINDOW_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MAIN_WINDOW_LEFT {
            get {
                return ((double)(this["MAIN_WINDOW_LEFT"]));
            }
            set {
                this["MAIN_WINDOW_LEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("420")]
        public double MAIN_WINDOW_HEIGHT {
            get {
                return ((double)(this["MAIN_WINDOW_HEIGHT"]));
            }
            set {
                this["MAIN_WINDOW_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("866")]
        public double MAIN_WINDOW_WIDTH {
            get {
                return ((double)(this["MAIN_WINDOW_WIDTH"]));
            }
            set {
                this["MAIN_WINDOW_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string MAIN_WINDOW_STATE {
            get {
                return ((string)(this["MAIN_WINDOW_STATE"]));
            }
            set {
                this["MAIN_WINDOW_STATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EXCLUDE_LIST {
            get {
                return ((string)(this["EXCLUDE_LIST"]));
            }
            set {
                this["EXCLUDE_LIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NAME_LIBRARY {
            get {
                return ((string)(this["NAME_LIBRARY"]));
            }
            set {
                this["NAME_LIBRARY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double PIN_MAP_HEIGHT {
            get {
                return ((double)(this["PIN_MAP_HEIGHT"]));
            }
            set {
                this["PIN_MAP_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double PIN_MAP_WIDTH {
            get {
                return ((double)(this["PIN_MAP_WIDTH"]));
            }
            set {
                this["PIN_MAP_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PIN_MAP_TOP {
            get {
                return ((double)(this["PIN_MAP_TOP"]));
            }
            set {
                this["PIN_MAP_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PIN_MAP_LEFT {
            get {
                return ((double)(this["PIN_MAP_LEFT"]));
            }
            set {
                this["PIN_MAP_LEFT"] = value;
            }
        }
    }
}
